spring:
  application:
    name: haruhana
  profiles:
    active: local
  config:
    import:
      - application-ai.yml
      - application-s3.yml
  web:
    resources:
      add-mappings: false
  jackson:
    time-zone: Asia/Seoul  # JSON 직렬화/역직렬화 시 타임존

server:
  tomcat:
    max-connections: 20000
    threads:
      max: 600
      min-spare: 100

---
spring.config.activate.on-profile: test
spring.config.import: application-test.yml

---
spring.config.activate.on-profile: local
spring.config.import: application-local.yml

---
spring.config.activate.on-profile: staging
spring.config.import: application-staging.yml

---
spring.config.activate.on-profile: prod
spring.config.import: application-prod.yml